#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#---Monitors---
bspc monitor DP-0 -d 1 2 3 4 5 6
bspc monitor DVI-D-0 -d 7 8 9

#---Config---
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#---Window rules---
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a discord
bspc rule -a spotify state=floating 
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# ---Autostart--- 
polybar &
dunst &
sh ~/.monitors.sh &
easyeffects --gapplication-service &
variety &
xinput set-prop "12" "libinput Accel Profile Enabled" 0 1 0
